### PR TITLE
Added spearmanr

### PR DESCRIPTION
**Pull request by sleighsoft**
Addresses issue https://github.com/lmcinnes/umap/issues/319 and https://github.com/lmcinnes/pynndescent/issues/85

I know tests are missing, but I am not 100% sure how to add them the right way. Guidance welcome.

### CODE REVIEW

**Comment by lmcinnes** [comment]
Thanks, this looks promising. For tests I think the custom distances require just testing things independently. You can probably just write a couple of tests, one that verifies that the ranking function works as intended, and one that just tests that the spearman distance outputs the results you would expect for some reasonable test vectors (a random example, and a few corner cases such as all 0 vectors, etc.)

**Comment by gokceneraslan** [comment]
Cool! Can you also check if all numpy calls are supported by numba's numpy support: https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

**Comment by lmcinnes** [comment]
Ideally this will happen once some tests exercise that code -- and then we can fix up any issues.

**Comment by sleighsoft** [comment]
I have this example working in a jupyter notebook. So it is definitely numba compatible.
Will add tests in the upcoming days.

**Comment by sleighsoft** [comment]
Tests added.

**Comment by lmcinnes** [comment]
It looks like it is just black formatting holding up the tests right now.

**Comment by sleighsoft** [comment]
Weird, I ran black on all of them

**Comment by lmcinnes** [comment]
I'm not really sure what the issue is; I'll just merge this and then deal with the fall-out from there. Thanks for submitting this!

**Pull request merged**
