### PR TITLE
Dropping Nose dependency and PyTest migration

### PR DESCRIPTION
**Pull request by leriomaggio**
As promised in [#578](https://github.com/lmcinnes/umap/pull/578#issuecomment-777023951), this PR migrates and rewrites `pynndescent` test suite to make it compatible with `pytest`.

In addition: 

- Python 3.8 pipelines have been added in CI
- CI scripts should be updated accordingly to use Pytest (with and without coverage support).

*EDIT*: Bear with me while I do test and fix CI scripts :)

### CODE REVIEW

**Comment by leriomaggio** [comment]
Ok so it seems that all the test passes, and all the CI test pipelines are doing OK. 

**Some notes**: 

1. I added new Testing Pipelines on all platforms for Python 3.8 (with and without coverage - but for Travis, **see 2**) - happy to do the same on UMAP if you like

2. I tried to re-enable the coverage on Travis but it is still not working. 

To try to replicate, I ran the testing command on my linux server with and without `NUMBA_JIT` but all the tests seemed to pass either way - so not entirely sure why this is happening on Travis.

Out of curiosity: Why is it necessary to disable `NUMBA_JIT`?

The rest seems to be working OK 👍 🙌

**Comment by lmcinnes** [comment]
Right now numba can't report back the information necessary for coverage tools to see code being used. This means that, with numba enabled, coverage tools see every numba jitted function as untouched and the coverage report is not very useful. The current workaround is to disable numba for coverage purposes. This has works for some things, but can get tangled up if we rely on certain aspects of numba -- in this case the pickleability of function closures. I might be able to fix that later.

Thanks so much for doing this. Keeping up with test infrastructure systems and CI setups is on my TODO list, but it is quite low, so I really have limited expertise and get stuck modifying a thing that worked before rather than moving to a better setup. Having someone who knows what they are doing come and modernize all of this is great, and it is going to make a lot of things easier going forward.

**Comment by leriomaggio** [comment]
Brilliant, thank you very much @lmcinnes for merging and for the explanation, now it makes much more sense!

Yes, I agree with you when you said that keeping the testing and CI pipelines up to date will help to make things a lot easier going forward! 🙌 

Happy to keep these pipelines updated either here as well as on `umap` repository!

Do you have any clue about the Travis TOKEN issue there? 
I will start adding support for Python 3.8 pipeline in umap too - so we will get ready for python 3.9 as well as latest numba will be released!

**Comment by lmcinnes** [comment]
I have little to no understanding of Travis, and pretty much just cargo-cult copy what others have done 'til things work. Sadly all of this is a bit outside of my expertise.

**Pull request merged**
