### PR TITLE
Random state was not being initialized correctly.

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Comment by tomwhite** [comment]
This was only a problem if `random_state=None` was passed to `NNDescent`.

**Comment by lmcinnes** [comment]
Thanks, feel free to merge it when you are ready. Sorry I haven't been spending much time on this lately, but I have been occupied with work and don't have a lot of time to spare at the moment.

**Comment by tomwhite** [comment]
Thanks @lmcinnes.

I haven't merged it yet as one of the tests is now failing, and I'm not sure why... It looks like having coverage turned on affects it in some way. Very odd.

**Comment by jlmelville** [comment]
That test is a regression test for the issue where UMAP was hanging due to lots of all-zero data and duplicates causing the rp-tree routine to recurse forever. Having that test just complete with a `RecursionError` is probably the true success, but having an admittedly arbitrary accuracy check was also useful (it did trigger during the backporting of UMAP 0.4 work).

In #41, I split the test into two, so the accuracy check should be less flaky, and merged into master. If you resync with master, hopefully the tests will pass.

**Comment by tomwhite** [comment]
Thanks for doing that @jlmelville! I've rebased, so let's see if that helps.

**Pull request merged**
